### ISSUE TITLE
New datastet

### ISSUE THREAD

**Issue by AbdulrhmnGhanem** [ElGarash/Al-Ajwad#13]
Download the https://api.qurancdn.com/api/qdc/audio/reciters?locale=en&fields=undefined.

Download all data, including all metadata.

**Comment by abdoei** [comment]
You can view this [Kaggle notebook](https://www.kaggle.com/code/abdo3id/notebook24a843b6bb/notebook) and its output is yet to be parsed for Arabic word, timestamps pairs to be easier to use.

**Comment by AbdulrhmnGhanem** [comment]
This is only the metadata, you need to add the audio files too!

**Comment by abdoei** [comment]
You may view this [Kaggle dataset](https://www.kaggle.com/datasets/abdo3id/quran-com-audio-files/data)
