### ISSUE TITLE
UIs

### ISSUE THREAD

**Issue by AbdulrhmnGhanem** [ElGarash/Al-Ajwad#4]
Create two UIs

1.  Playground: in which a user can test the final version of the model
2.  Annotator: used by human annotators to annotate the segmented audio

**Comment by AbdulrhmnGhanem** [comment]
Fix the text color for the `Diff` field in dark mode.

![image](https://github.com/ElGarash/Al-Ajwad/assets/37152329/c37af016-6619-48fe-af0b-782ae583238c)

**Comment by abdoei** [comment]
Done
you can check it out at this [link](https://93759fb02235ae8295.gradio.live/) for an hour from now or you can run the [notebook](https://colab.research.google.com/drive/1DdNiR5J5ziVEkIShLuTu4DyYLlK52cmB) yourself
<p>
  <img src="https://github.com/ElGarash/Al-Ajwad/assets/64744285/093eeb52-b34a-43f6-bc1d-6f05d72c87cb" alt="Image 1" width="200" />
  <img src="https://github.com/ElGarash/Al-Ajwad/assets/64744285/d2645dc6-dbfc-4f46-8bdb-8ca70950d3a8" alt="Image 2" width="200" />
</p>
