### ISSUE TITLE
Keep the Ayat in which the model doesn't score zero `WER` as notebook output

### ISSUE THREAD

**Issue by AbdulrhmnGhanem** [ElGarash/Al-Ajwad#5]

**Comment by OmarTariq612** [comment]
Here is the notebook: https://www.kaggle.com/code/omartariq612/non-zero-wer/notebook

**Comment by AbdulrhmnGhanem** [comment]
## WER
![image](https://github.com/ElGarash/Al-Ajwad/assets/37152329/8590e8ce-f358-47f0-ad11-583fa1e7b199)

## AER
![image](https://github.com/ElGarash/Al-Ajwad/assets/37152329/8718b66e-3b71-4325-861c-de613a0776fc)
